handler: lambdas/get-apps/get-apps.handler
name: get-apps
layers:
  - { Ref: ApiLayerLambdaLayer }
package:
  include:
    - lambdas/get-apps/get-apps.js
    - lambdas/get-apps/helpers/**
events:
  - http:
      method: get
      path: /
      cors: true
      kaskadi-docs:
        description: This endpoint lists all applications available for the Kaskadi project.
