handler: lambdas/get-apps/get-apps.handler
name: get-apps
layers:
  - { Ref: ApiLayerLambdaLayer }
package:
  include:
    - lambdas/get-apps/get-apps.js
    - lambdas/get-apps/helpers/**
events:
  - http:
      method: get
      path: /
      cors: true
      kaskadi-docs:
        description: This endpoint lists all applications available for the Kaskadi project.
        examples:
          - request: {}
            response:
              body:
                - listed: true
                  title:
                    en: Accounting
                    de: Buchhaltung
                    fr: Comptabilité
                  section: finance
                  main: kaskadi-accounting.js
                  description:
                    en: Accounting app
                    de: Buchhaltung
                    fr: Application pour la comptabilité
                  routes:
                    - path: /finance/accounting
                      appPath: /modules/@kaskadi/kaskadi-apps/kaskadi-accounting/kaskadi-accounting.js
                - listed: false
                  title:
                    en: APP-TITLE-ENGLISH
                    de: APP-TITLE-GERMAN
                    fr: APP-TITLE-FRENCH
                  section: ''
                  main: kaskadi-dashboard.js
                  description:
                    en: APP-DESCRIPTION-ENGLISH
                    de: APP-DESCRIPTION-GERMAN
                    fr: APP-DESCRIPTION-FRENCH
                  routes:
                    - path: /
                      appPath: /modules/@kaskadi/kaskadi-apps/kaskadi-dashboard/kaskadi-dashboard.js
              statusCode: 200
              headers:
                'Access-Control-Allow-Origin': "*"
